---
- name: "{{ role_name }} | {{ task.name }} | Check for active repositories of type lab"
  ansible.builtin.debug:
    msg: "It is necessary to ensure the {{ labs_dir }} directory"
  register: active_lab_repos
  when: "(cac_git_repos
    | selectattr('enabled', 'search', 'true')
    | selectattr('type', 'search', 'lab')
    | list )"

- name: "{{ role_name }} | {{ task.name }} | Ensure the {{ labs_dir }} directory"
  ansible.builtin.file:
    path: "{{ labs_dir }}"
    state: directory
    mode: '0750'
  register: result_labs_dir
  when:
    # result_cac_base_dir is defined in configure_env
    - result_cac_base_dir is success
    - active_lab_repos is not skipped

- name: "{{ role_name }} | {{ task.name }} | Ensure the labs repositories are updated"
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ labs_dir }}/{{ item.dest }}"
    clone: true
    update: true
  loop: "{{ cac_git_repos }}"
  when:
    - item.enabled
    - item.type == "lab"
    - result_labs_dir is success

- name: "{{ role_name }} | {{ task.name }} | Ensure Vagrant files for test VMs"
  ansible.builtin.copy:
    dest: "{{ labs_dir }}"
    mode: '0640'
    src: "{{ role_path }}/files/VMs"
    force: yes
    backup: yes
  register: result_vms_content
  when:
    - result_labs_dir is success

- name: "{{ role_name }} | {{ task.name }} | Read the instructions files for Labs"
  ansible.builtin.debug:
    msg:
      - "Please, read the information and follow the instructions in the {{ item }} file."
  loop: "{{ vms_instructions_files }}"
  when:
    - result_vms_content is success
...
