---
- name: "{{ role_name }} | {{ task.name }} | Ensure the desired Linux repositories"
  become: true
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.repo }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    enabled: yes
    state: "{{ item.state }}"
  loop: "{{ cac_linux_repos }}"
  when:
    - item.enabled
    - ansible_facts['os_family']|lower == "redhat"

- name: "{{ role_name }} | {{ task.name }} | Ensure all packages are installed"
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
...
