---
- name: "{{ role_name }} | {{ task.name }} | Ensure the forked Git repositories are updated"
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ forks_dir }}/{{ item.dest }}"
    clone: true
    update: true
  loop: "{{ git_repos }}"
  register: result_git_fork
  ignore_errors: true
  when:
    - item.enabled
    - item.type == "fork"
    # result_forks_dir is defined in configure_env
    - result_forks_dir is success

- name: "{{ role_name }} | {{ task.name }} | Check if the desired remote references are present"
  ansible.builtin.lineinfile:
    name: "{{ forks_dir }}/{{ item.dest }}/.git/config"
    line: '[remote "{{ item.remote_name }}"]'
    state: absent
  loop: "{{ git_repos }}"
  register: result_git_remote_check
  check_mode: true
  changed_when: false
  when:
    - item.enabled
    - item.type == "fork"
    - result_git_fork is success

- name: "{{ role_name }} | {{ task.name }} | Add remote references for forked Git repositories"
  ansible.builtin.command:
    chdir: "{{ forks_dir }}/{{ item.item.dest }}"
    cmd: "git remote add {{ item.item.remote_name }} {{ item.item.remote }}"
  loop: "{{ result_git_remote_check.results }}"
  register: result_git_remote_add
  when:
    - item is not skipped
    - item.found == 0

- name: "{{ role_name }} | {{ task.name }} | Ensure the forked Git repositories have desired remote references"
  community.general.ini_file:
    path: "{{ forks_dir }}/{{ item.dest }}/.git/config"
    section: 'remote "{{ item.remote_name }}"'
    option: url
    value: "{{ item.remote }}"
  loop: "{{ git_repos }}"
  when:
    - item.enabled
    - item.type == "fork"
    - result_git_remote_add is skipped

- name: "{{ role_name }} | {{ task.name }} | Ensure the main instructions files"
  ansible.builtin.copy:
    dest: "{{ base_dir }}"
    mode: '0664'
    src: "{{ role_path }}/files/{{ item }}"
    force: true
    backup: true
  loop: "{{ general_instructions_files }}"
  when:
    # result_base_dir is defined in configure_env
    - result_base_dir is success
...
