# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # VMs will be created using libvirt, with 2GB of RAM and 2 vcpus
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = "2048"
    libvirt.cpus = 2
    libvirt.default_prefix = "cac_"
    libvirt.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
  end

  # This Vagrantfile is using a publicly available Box and, therefore, without
  # a valid subscription. This BOX does not include some required packages to
  # properly test CaC content. Therefore, to be able to use it you need to
  # interactively include your subscription after the VM is ready or customize
  # the "bootstrap" script below, to include the subscription-manager commands
  # with the proper values.
  #
  # Alternativaly, if you have testing repositories, you can set them in the
  # variables below and enable them in the provision time by setting the variable
  # RHEL_ENABLED_REPOS to 1.
  RHEL_BASE_REPO = "http://example.com/BaseOS/x86_64/os/"
  RHEL_APPS_REPO = "http://example.com/AppStream/x86_64/os/"
  RHEL_ENABLE_REPOS = "0"

  $rhel_testing_repos = <<-SCRIPT
echo "
[cac_base_repo]
name=CaC Testing Base Repo
baseurl=#{RHEL_APPS_REPO}
enabled=#{RHEL_ENABLE_REPOS}
gpgcheck=0

[cac_apps_repo]
name=CaC Testing Apps Repo
baseurl=#{RHEL_APPS_REPO}
enabled=#{RHEL_ENABLE_REPOS}
gpgcheck=0" > /etc/yum.repos.d/cac.repo
  SCRIPT
  config.vm.provision "shell", inline: $rhel_testing_repos

  # This script will be executed for all VMs for general customization.
  # If you want to customize something in your VM during its provisioning, here
  # is the place. You can write shell script language between "-SCRIPT" and "SCRIPT".
  # This will be executed inside the VM, post-installation.
  ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
  $bootstrap = <<-SCRIPT
  mkdir -p touch /root/.ssh
  echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
  echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
  useradd -G wheel admin && echo "admin123" | passwd --stdin admin
  dnf install openscap-scanner openscap-engine-sce tar qemu-guest-agent openssh-clients openssh-server vim -y
  SCRIPT
  config.vm.provision "shell", inline: $bootstrap

  # Here we are actually defining the Box image and the VM name to be provisioned.
  # If you want another version, you can change here.
  VM_NAME = "rhel8"
  VM_BOX = "generic/rhel8"

  config.vm.define VM_NAME do |rhel|
    rhel.vm.box = VM_BOX
    rhel.vm.hostname = VM_NAME
  end

end
