---
# This file has the custom variables for configure_env task.

path_env:
  - { enabled: false,  name: 'just informative name',
      path: '{{ forks_dir }}/project-tools/bin' }
  - { enabled: false,  name: 'Compiled OpenSCAP Binaries',
      path: '{{ forks_dir }}/OpenSCAP/openscap/build' }

user_env_file: "{{ ansible_facts['user_dir'] }}/.bashrc"

# This module will increment the PYTHONPATH environment for "utils" tools.
# source .pyenv.sh is a shortcut to also load the ssg module, used by utils tools.
#pythonpath_env:
#  - { enabled: False,  name: 'Content Specific Python Modules',
#      path: '{{ upstream_dir }}/ComplianceAsCode/content/utils' }
...
