---
# This file has the custom configurations for configure_vscode task.

vscode_repo:
  - { enabled: true,  state: 'present', name: 'VSCode',
      description: 'Visual Studio Code',
      repo: 'https://packages.microsoft.com/yumrepos/vscode', 
      gpgcheck: '1', 
      gpgkey: 'https://packages.microsoft.com/keys/microsoft.asc' }

vscode_workspaces_folder: "{{ ansible_facts['user_dir'] }}/.config/Code/Workspaces"
vscode_workspaces_config_file: "workspace.json"

# The "installed" parameter determines if the extension will be installed or removed.
# Note that if your VSCode is opened, may be needed to restart it to commit some
# extensions changes. Be conservative with extensions because every single new extension
# is a extra load to your VSCode. You probably want to increase its efficiency instead of
# making it slower. But, if including extensions, organize them by reasonable categories
# and alphabetically within categories.
vscode_extensions:
  # Extensions to avoid typos and allow better comments
  - { enabled: true,  installed: true,  name: 'adamvoss.vscode-languagetool-en' }
  - { enabled: true,  installed: true,  name: 'adamvoss.vscode-languagetool' }
  - { enabled: true,  installed: true,  name: 'streetsidesoftware.code-spell-checker' }
  # Extensions for specific languages and formats
  - { enabled: true,  installed: true,  name: 'docsmsft.docs-markdown' }
  - { enabled: true,  installed: true,  name: 'golang.Go' }
  - { enabled: true,  installed: true,  name: 'laurenttreguier.rpm-spec' }
  - { enabled: true,  installed: true,  name: 'maelvalais.autoconf' }
  - { enabled: true,  installed: true,  name: 'ms-azuretools.vscode-docker' }
  - { enabled: true,  installed: true,  name: 'ms-python.python' }
  - { enabled: true,  installed: true,  name: 'ms-vscode.cmake-tools' }
  - { enabled: true,  installed: true,  name: 'ms-vscode.cpptools' }
  - { enabled: true,  installed: true,  name: 'redhat.ansible' }
  - { enabled: true,  installed: true,  name: 'redhat.vscode-yaml' }
  - { enabled: true,  installed: true,  name: 'shd101wyy.markdown-preview-enhanced' }
  - { enabled: true,  installed: true,  name: 'timonwong.shellcheck' }
  - { enabled: true,  installed: true,  name: 'xaver.clang-format' }
  # Extensions for better visualization
  - { enabled: true,  installed: true,  name: 'coenraads.bracket-pair-colorizer-2' }
  - { enabled: true,  installed: true,  name: 'eamodio.gitlens' }
  - { enabled: true,  installed: true,  name: 'ggbecker.content-navigator' }
  - { enabled: true,  installed: true,  name: 'leodevbro.blockman' }
  - { enabled: true,  installed: true,  name: 'vscode-icons-team.vscode-icons' }

# You can have more folders in the same Workspace or more Workspaces.
# In this case, we are including the "main_dir" folder in the existing workspace.
vscode_workspaces:
  - { enabled: true, state: 'directory', action: 'add', name: 'OpenSCAP', path: '{{ base_dir }}' }
...
